#!/bin/bash

# Common script utilities
source $(cd $(dirname $BASH_SOURCE) &> /dev/null && pwd)/../../build/make/shell_utils.sh

require_top

cd $TOP

sudo rm -rf out && \
repo sync -j 16 --force-sync
