name: Run CI Tool

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ secrets.GH_TOKEN }} # setting GH_TOKEN for the entire workflow

jobs:
  ci-tool:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Deps
      run: sudo apt install -y libgtk-4-1 libgtk-4-dev libadwaita-1-0 libadwaita-1-dev
    - name: Configure git
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - name: Run CI Tool
      run: |
       cd jOS/source/ci-tool
       cargo run --release
